CREATE TABLE IF NOT EXISTS NOBEL_WINS (
 YEAR INTEGER,
 SUBJECT TEXT,
 WINNER TEXT,
 COUNTRY TEXT,
 CATEGORY TEXT
);

INSERT INTO NOBEL_WINS (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
 (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
 (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCIENTIST'),
 (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCIENTIST'),
 (1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
 (1972, 'LITERATURE', 'BERNARD KELSON', 'GERMANY', 'ECONOMIST'),
 (1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
 (1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
 (1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
 (1981, 'PHYSIOLOGY', 'HANNAH', 'HUNGARY', 'SCIENTIST'),
 (1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');

SELECT * FROM NOBEL_WINS;

-- Select all records ehere the subject doesn't start with 'P'
SELECT * FROM NOBEL_WINS
WHERE SUBJECT NOT LIKE 'P%';


SELECT WINNER || '(' || SUBSTR(SUBJECT, 1, 1) || ')' AS WINNER FROM NOBEL_WINS; --)column_name, start, steps)

-- HANNES ALFVEN (p) etc.